name: myketiap_example
description: Demonstrates how to use the myketiap plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  myket_iap:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/buy_gas.png
    - assets/drive.png
    - assets/free.png
    - assets/gas0.png
    - assets/gas1.png
    - assets/gas2.png
    - assets/gas3.png
    - assets/gas4.png
    - assets/gas_inf.png
    - assets/get_infinite_gas.png
    - assets/ic_launcher.png
    - assets/manage_infinite_gas.png
    - assets/premium.png
    - assets/title.png
    - assets/upgrade_app.png
    - assets/wait.png