name: myket_iap
description: Myket IAP plugin for flutter
version: 1.0.0
homepage: https://myket.ir

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ir.mservices.myketiap
        pluginClass: MyketPlugin